### PR TITLE
[Documentation] Introducing the directives

### PR DESCRIPTION
**Pull request by equetzal**
[Documentation] Introducing the directives

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/equetzal/huronOS-build-tools/pull/142).
* #154
* #143
* __->__ #142

### CODE REVIEW

**Comment by equetzal** [comment]
Sending ChatGPT rewrite

**Comment by equetzal** [comment]
@DT3264 Asking for dev review of the content.

**Review by DT3264 — APPROVED** [review]
LGTM

**Comment by equetzal** [comment]
@alex-gorod for english review please :D

**Pull request merged**
