### PR TITLE
[Documentation] Adding source control

### PR DESCRIPTION
**Pull request by equetzal**
[Documentation] Adding source control

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/equetzal/huronOS-build-tools/pull/126).
* #127
* __->__ #126

### CODE REVIEW

**Comment by equetzal** [comment]
Sending rewrote version by chatGPT

**Comment by equetzal** [comment]
Asking for developers to review for accuracy.
@DT3264

**Review by DT3264 — APPROVED** [review]
LGTM

**Comment by equetzal** [comment]
English reviewers to validate
@alex-gorod

**Comment by equetzal** [comment]
Merging for lack of review from english professionals.

**Comment by alex-gorod** [comment]
@equetzal  I didn't receive any notification on my e-mail and just realized I've been tagged, sorry, but just read it and doesn't seem to have any errors to me. So it is good to go.

**Pull request merged**
