### PR TITLE
Adds systembus-notify (earlyoom notifications)

### PR DESCRIPTION
**Pull request by DT3264**
earlyoom sends messages through a bus channel, [this](https://github.com/rfjakob/systembus-notify) app listens to that channel, although there's no .deb available so it has to be manually compiled. 
The only thing that was modified was the default time for notifications which was -1 (the default notification time specified by budgie) and I didn't knew how to update that value, so I set it to 5 (I think 5 seconds is enough time to see the notification).

### CODE REVIEW

**Comment by DT3264** [comment]
Once #90 is merged, I'll rebase that to keep the last commit which is the only one relevant to this PR

**Comment by equetzal** [comment]
> Once #90 is merged, I'll rebase that to keep the last commit which is the only one relevant to this PR

I think basing on prev branch and after merging previous branch this one should be automatically based to unstable

**Comment by equetzal** [comment]
Not sure of how notifications look like. So this allows earlyoom to send a GUI notification? 
If so, can we change this meesage?

**Review by equetzal — APPROVED** [review]

**Comment by DT3264** [comment]
@equetzal 
My bad on not answering before :sweat_smile:, this is how a notification that a process has been killed looks like.
And yep, it's possible to change the message, either modifying the earlyoom source to change the message, or modifying the notifications source, if you'd like to set another message let me know and I'll work on it. 
Untitled

**Pull request merged**
